INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Lucas', 'Marques', 'lucas@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Lara', 'Cobar', 'lara@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_GUEST');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('The Lord of the Rings', "The lord of the Ring is a fantasy book", "J. R. R. Tolkien", "FANTASY", 1568, "Harper Collins", 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('Flores para Algernon', "Is a book about a man and a rat", "Daniel Keyes", "ROMANCE", 288, "Editora Aleph", 'https://editoraaleph.com.br/wp-content/uploads/2020/09/Alp_1SiteNovo_4CadastroSimples_FloresAlgernon-1.png');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('The Lord of the Rings', "The lord of the Ring is a fantasy book", "J. R. R. Tolkien", "FANTASY", 1568, "Harper Collins", 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('Flores para Algernon', "Is a book about a man and a rat", "Daniel Keyes", "ROMANCE", 288, "Editora Aleph", 'https://editoraaleph.com.br/wp-content/uploads/2020/09/Alp_1SiteNovo_4CadastroSimples_FloresAlgernon-1.png');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('The Lord of the Rings', "The lord of the Ring is a fantasy book", "J. R. R. Tolkien", "FANTASY", 1568, "Harper Collins", 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('Flores para Algernon', "Is a book about a man and a rat", "Daniel Keyes", "ROMANCE", 288, "Editora Aleph", 'https://editoraaleph.com.br/wp-content/uploads/2020/09/Alp_1SiteNovo_4CadastroSimples_FloresAlgernon-1.png');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('The Lord of the Rings', "The lord of the Ring is a fantasy book", "J. R. R. Tolkien", "FANTASY", 1568, "Harper Collins", 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('Flores para Algernon', "Is a book about a man and a rat", "Daniel Keyes", "ROMANCE", 288, "Editora Aleph", 'https://editoraaleph.com.br/wp-content/uploads/2020/09/Alp_1SiteNovo_4CadastroSimples_FloresAlgernon-1.png');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('The Lord of the Rings', "The lord of the Ring is a fantasy book", "J. R. R. Tolkien", "FANTASY", 1568, "Harper Collins", 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('Flores para Algernon', "Is a book about a man and a rat", "Daniel Keyes", "ROMANCE", 288, "Editora Aleph", 'https://editoraaleph.com.br/wp-content/uploads/2020/09/Alp_1SiteNovo_4CadastroSimples_FloresAlgernon-1.png');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('The Lord of the Rings', "The lord of the Ring is a fantasy book", "J. R. R. Tolkien", "FANTASY", 1568, "Harper Collins", 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_book (name, description, author, literaryGenreEnum, numberOfPages, publishingCompany, image) VALUES ('Flores para Algernon', "Is a book about a man and a rat", "Daniel Keyes", "ROMANCE", 288, "Editora Aleph", 'https://editoraaleph.com.br/wp-content/uploads/2020/09/Alp_1SiteNovo_4CadastroSimples_FloresAlgernon-1.png');
